name: Generate changelog

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current and previous tags
        run: |
          git fetch --tags
          current_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')
          previous_tag=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1` || echo '')
          if [ -z "$previous_tag" ]; then
            echo "No previous tags found (first release). Using first commit as previous_tag."
            previous_tag=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "current_tag=$current_tag" >> $GITHUB_ENV
          echo "previous_tag=$previous_tag" >> $GITHUB_ENV
          echo "Previous Tag: $previous_tag"
          echo "Current Tag: $current_tag"

      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v2.2.2
        if: env.previous_tag && env.current_tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          show-emoji: false
          base-ref: ${{ env.previous_tag }}
          template: |
            ## Bugs
            {{fix}}
            ## Feature
            {{feat}}
            ## Improve
            {{refactor,perf,clean}}
            ## Misc 
            {{chore,style,ci||🔶 Nothing change}}
            ## Unknown
            {{__unknown__}}

      - name: Show the changelog
        if: env.previous_tag && env.current_tag
        run: echo "${{ steps.changelog.outputs.changelog }}"

      - name: Update Release
        uses: softprops/action-gh-release@v2
        if: env.previous_tag && env.current_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.current_tag }}
          body: |
            ${{ steps.changelog.outputs.compareurl }}
            
            ${{ steps.changelog.outputs.changelog }}